name: "hello world!"
on: [push]
jobs:
  hello-world: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: echo "🎉 Node.js v18 has been installed."
      - name: Run a one-line script
      - run: node index.js